### ISSUE TITLE
PCB files missing

### ISSUE THREAD

**Issue by tim-hilt** [splitkb/kyria#15]
Hi there! I am literally building an Aurora Corne that I ordered from you right now. I really enjoyed your service and the fast delivery to Germany.

I would like to build a Kyria next and wanted to take a stab at ordering PCBs myself. Are you seeing yourself releasing the Gerber-files on here anytime soon?

The Kyria is an awesome layout and I‘d understand if open-sourcing is not an option from a business-standpoint.

**Comment by splitkb** [comment]
The PCB files are deliberately not open source, in order to support our livelihood :) Thank you for your interest!

**Comment by tim-hilt** [comment]
Makes total sense. Thanks for the response though! I'll order it from you then :D
